"""create runs table

Revision ID: 3c48e0cfa3e1
Revises: 11d12275fb2c
Create Date: 2026-08-25 18:11:10.982343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c48e0cfa3e1'
down_revision: Union[str, Sequence[str], None] = '11d12275fb2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_message_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('model_provider', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed', 'cancelled')", name='ck_runs_status'),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_session_id_created_at', 'runs', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_runs_status_created_at', 'runs', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_runs_status_created_at', table_name='runs')
    op.drop_index('ix_runs_session_id_created_at', table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
