"""link messages to runs

Revision ID: 60cab443f97a
Revises: d177e6f7fce7
Create Date: 2026-08-27 20:26:20.456554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60cab443f97a'
down_revision: Union[str, Sequence[str], None] = 'd177e6f7fce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('run_id', sa.Uuid(), nullable=True))
    op.create_index('ix_messages_run_id_created_at', 'messages', ['run_id', 'created_at'], unique=False)
    op.create_foreign_key(
        'fk_messages_run_id_runs',
        'messages',
        'runs',
        ['run_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_messages_run_id_runs',
        'messages',
        type_='foreignkey',
    )
    op.drop_index('ix_messages_run_id_created_at', table_name='messages')
    op.drop_column('messages', 'run_id')
    # ### end Alembic commands ###
